name: formadziri
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  flutter_native_splash: ^2.2.19
  smooth_page_indicator: ^1.1.0
  dynamic_color: ^1.6.3
  share_plus: ^6.3.4
  flutter_localizations:
    sdk: flutter
    version: ^0.0.0
  intl: ^0.18.0
  marquee: ^2.2.3
  text_scroll: ^0.2.0
  percent_indicator: ^4.2.3
  cached_network_image: ^3.2.3
  audio_video_progress_bar: ^1.0.1
  just_audio: ^0.9.34
  just_audio_background: ^0.0.1-beta.10
  rxdart: ^0.27.7
  dio: ^5.3.0
  get: ^4.6.5
  simple_autocomplete_formfield: ^0.3.0
  cloud_firestore: ^4.8.4
  firebase_core: ^2.15.0



flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#6D8A6B"
  image: "images/translogo.png"
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_gen: ^5.3.1

flutter:

  generate: true
  uses-material-design: true

  assets:

    - images/
    - assets/images/
    - images/nav/
    - images/srch/
    - images/lang/
    - images/crs/
    - images/bac/
    - images/avatars/

  fonts:
    - family: Goudy
      fonts:
        - asset: assets/fonts/Goudy.ttf
